Add Zeitwerk loader support
ATIX-AG/foreman_snapshot_management pull request #105
Opened 2024-10-09 13:42 UTC by nadjaheitmann

2024-10-14 09:03 UTC, dosas requested changes
I do not get why the tests are failing due to backwards compatibility since the failing tests are all for ruby >=3.

Dropping the tests is not an option.

2024-10-14 09:07 UTC, nadjaheitmann commented on .rubocop.yml
> +    - 'lib/foreman_snapshot_management/engine.rb'
I think the metric is mainly to keep complexity for functions as simple as possible. As this not really complies with this rule, I think it is okay to add this file.

2024-10-14 09:25 UTC, dosas commented on .rubocop.yml
> +    - 'lib/foreman_snapshot_management/engine.rb'
I think in that case we should exclude the rule not the complete file.

2024-10-14 09:26 UTC, dosas commented
> > I do not get why the tests are failing due to backwards compatibility since the failing tests are all for ruby >=3.
> 
> It is because I adjusted to work foreman_snapshot_management master branch to work Foreman develop which uses Zeitwerk. But Zeitwerk is not used for Foreman 3.11 and 3.12 . Hence, this is a breaking change.
> 
> The pipeline always checks against the master branch of this foreman_snapshot_management, no matter what happens in upstream Foreman. So the problem is that the pipeline somehow expect that the plugin is always backwards compatible which it is not. And what is okay, I think, the same happens for all upstream plugins.

In that case everything is working as expected (develop: green, 3.11 and 3.12: red) 
I would opt for feature branches until 3.13 is released.

2024-10-14 09:41 UTC, nadjaheitmann commented
> In that case everything is working as expected (develop: green, 3.11 and 3.12: red) 

Definitely, we just need to decide how to deal with that.

> I would opt for feature branches until 3.13 is released.

I would suggest to bump a version before merging this and then add a feature branch `3.0-stable` .

2024-10-14 10:17 UTC, nadjaheitmann commented
> > In that case everything is working as expected (develop: green, 3.11 and 3.12: red)
> 
> Definitely, we just need to decide how to deal with that.
> 
> > I would opt for feature branches until 3.13 is released.
> 
> I would suggest to bump a version before merging this and then add a feature branch `3.0-stable` .

Actually, there are no significant new features, so we probably do not need to bump a new version. I added a new branch for foreman_snapshot_management version 3.x.x which does not run tests on the develop branch https://github.com/ATIX-AG/foreman_snapshot_management/tree/3.0-stable.

2024-10-21 07:15 UTC, dosas approved these changes

2024-10-21 07:56 UTC, merged